local lines = {
	"May I have a name please?";
	"Robert Loggia.";
	"Can you spell that for me?";
	"Certainly. That's:";
	"Robert Loggia.";
	"R, as in Robert Loggia,";
	"O, as in Oh my god it's Robert Loggia,";
	"B, as in By god that's Robert Loggia,";
	"E, as in Everybody loves Robert Loggia,";
	"R, as in Robert Loggia,";
	"T, as in Tim, look over there, it's Robert Loggia!";
	"Space.";
	"L, as in Look, it's Robert Loggia!";
}
for i, v in ipairs(lines) do
	print(v)
end
